
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Reddit_Visualizer_development

test:
  <<: *default
  database: Reddit_Visualizer_test

production:
  <<: *default
  database: Reddit_Visualizer_production
  username: Reddit_Visualizer
  password: <%= ENV['REDDIT_VISUALIZER_DATABASE_PASSWORD'] %>